server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  ssl:
    enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false

logging:
  level:
    root: debug

